spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:batchdb
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false

logging:
  structured:
    format: text
  level:
    com.example: DEBUG
